[world]
kind = "WorldContract"
class_hash = "0x279d12a282d7888e3fdbe456150775be2c160e7c78d409bbf02be68fdf275ce"
original_class_hash = "0x279d12a282d7888e3fdbe456150775be2c160e7c78d409bbf02be68fdf275ce"
abi = "manifests/mainnet/deployment/abis/dojo-world.json"
address = "0x53e0ba5aa2cc9cf3b21ffaf0d0e9407eab627b759404e35e69e8d3e6f1e3616"
transaction_hash = "0x604b056dfbb2c1207d811c687bf9a6cb483e951377f66793c95c663cd70b2c3"
seed = "flippyflop-mainnet"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "mainnet"
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/mainnet/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x1bfe97d729138fc7c2d93c77d6d1d8a24708d5060608017d9b384adf38f04c7"
class_hash = "0x683a4555da17fdd63478e6b096f7cbb3fc8b02dcfdaa361fb2c712a14241abb"
original_class_hash = "0x683a4555da17fdd63478e6b096f7cbb3fc8b02dcfdaa361fb2c712a14241abb"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/mainnet/deployment/abis/contracts/flippyflop-Flip-6bd3ed9d.json"
reads = []
writes = []
init_calldata = []
tag = "flippyflop-Flip"
systems = [
    "burn",
    "burn_from",
    "mint",
    "before_update",
    "after_update",
]
manifest_name = "flippyflop-Flip-6bd3ed9d"

[[contracts]]
kind = "DojoContract"
address = "0xa5196fcad0b16ab0863fa741813e95f178ca50b2b84593255c6dd899a70a78"
class_hash = "0x61d4915fb37b0ba3d4fbcd1a3369f67c811670fcbfc6ea34df8250d952ba980"
original_class_hash = "0x61d4915fb37b0ba3d4fbcd1a3369f67c811670fcbfc6ea34df8250d952ba980"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/mainnet/deployment/abis/contracts/flippyflop-actions-4407e5f5.json"
reads = []
writes = [
    "flippyflop-Tile",
    "flippyflop-Game",
    "flippyflop-Claim",
]
init_calldata = []
tag = "flippyflop-actions"
systems = [
    "flip",
    "flop",
    "claim",
]
manifest_name = "flippyflop-actions-4407e5f5"

[[contracts]]
kind = "DojoContract"
address = "0x40c77fb92999766ed4c620f2c8ffe6298ecebc873c23c829beaf1f21ac24ec6"
class_hash = "0x387fe3fc7f75da12e272a16afa22084a793c954b0171ea7256d5643b27ae6b0"
original_class_hash = "0x387fe3fc7f75da12e272a16afa22084a793c954b0171ea7256d5643b27ae6b0"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/mainnet/deployment/abis/contracts/flippyflop-game-23e1ad43.json"
reads = []
writes = ["flippyflop-Game"]
init_calldata = []
tag = "flippyflop-game"
systems = ["set_game"]
manifest_name = "flippyflop-game-23e1ad43"

[[models]]
kind = "DojoModel"
class_hash = "0x7416d8eddcdb8106e3574223f03624a8290f2f012c5c4d628383d3ccb8a56a0"
original_class_hash = "0x7416d8eddcdb8106e3574223f03624a8290f2f012c5c4d628383d3ccb8a56a0"
abi = "manifests/mainnet/deployment/abis/models/flippyflop-Claim-c098f39e.json"
tag = "flippyflop-Claim"
qualified_path = "flippyflop::models::claim"
manifest_name = "flippyflop-Claim-c098f39e"

[[models.members]]
name = "player"
type = "felt252"
key = true

[[models.members]]
name = "amount"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4588722084c4cba1610d93e810d1c4dd557b6b23dce920fd121218eb1a9a56d"
original_class_hash = "0x4588722084c4cba1610d93e810d1c4dd557b6b23dce920fd121218eb1a9a56d"
abi = "manifests/mainnet/deployment/abis/models/flippyflop-FlipBalance-607c056d.json"
tag = "flippyflop-FlipBalance"
qualified_path = "flippyflop::tokens::flip::Flip::flip_balance"
manifest_name = "flippyflop-FlipBalance-607c056d"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "balance"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x57ead6063326effcdf7b2a7ba32e7931e789d96d3151a7fb050853283798095"
original_class_hash = "0x57ead6063326effcdf7b2a7ba32e7931e789d96d3151a7fb050853283798095"
abi = "manifests/mainnet/deployment/abis/models/flippyflop-Game-54c54faf.json"
tag = "flippyflop-Game"
qualified_path = "flippyflop::models::game"
manifest_name = "flippyflop-Game-54c54faf"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "data"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4a4abfcb39d8c9935eaf1c96eda1ee3df8d448992e11a58fb3bc62821a14d20"
original_class_hash = "0x4a4abfcb39d8c9935eaf1c96eda1ee3df8d448992e11a58fb3bc62821a14d20"
abi = "manifests/mainnet/deployment/abis/models/flippyflop-Tile-61fb9291.json"
tag = "flippyflop-Tile"
qualified_path = "flippyflop::models::tile"
manifest_name = "flippyflop-Tile-61fb9291"

[[models.members]]
name = "x"
type = "u32"
key = true

[[models.members]]
name = "y"
type = "u32"
key = true

[[models.members]]
name = "flipped"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x69a62266a511f2937f5c08976de5b8a2455acbe622bc8d6060616282832eb66"
original_class_hash = "0x69a62266a511f2937f5c08976de5b8a2455acbe622bc8d6060616282832eb66"
abi = "manifests/mainnet/deployment/abis/models/flippyflop-User-25ca4606.json"
tag = "flippyflop-User"
qualified_path = "flippyflop::models::user"
manifest_name = "flippyflop-User-25ca4606"

[[models.members]]
name = "identity"
type = "ContractAddress"
key = true

[[models.members]]
name = "last_message"
type = "ByteArray"
key = false

[[models.members]]
name = "hovering_tile_x"
type = "u32"
key = false

[[models.members]]
name = "hovering_tile_y"
type = "u32"
key = false
