kind = "DojoModel"
class_hash = "0x7416d8eddcdb8106e3574223f03624a8290f2f012c5c4d628383d3ccb8a56a0"
original_class_hash = "0x7416d8eddcdb8106e3574223f03624a8290f2f012c5c4d628383d3ccb8a56a0"
abi = "manifests/mainnet/base/abis/models/flippyflop-Claim-c098f39e.json"
tag = "flippyflop-Claim"
qualified_path = "flippyflop::models::claim"
manifest_name = "flippyflop-Claim-c098f39e"

[[members]]
name = "player"
type = "felt252"
key = true

[[members]]
name = "amount"
type = "u256"
key = false
