kind = "DojoModel"
class_hash = "0x69800345431696738834bc1aa3ade287b67e44391138f473748fbbd4c95bd9a"
original_class_hash = "0x69800345431696738834bc1aa3ade287b67e44391138f473748fbbd4c95bd9a"
abi = "manifests/sepolia/base/abis/models/flippyflop-InitializableModel-4239d2f3.json"
tag = "flippyflop-InitializableModel"
qualified_path = "origami_token::components::security::initializable::initializable_model"
manifest_name = "flippyflop-InitializableModel-4239d2f3"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "initialized"
type = "bool"
key = false
