kind = "DojoModel"
class_hash = "0x491a48fb74ba9e09baa7cd0c7b518557a4c422b85bb7a72782a98ab8c89bcf2"
original_class_hash = "0x491a48fb74ba9e09baa7cd0c7b518557a4c422b85bb7a72782a98ab8c89bcf2"
abi = "manifests/sepolia/base/abis/models/flippyflop-ERC20AllowanceModel-55d0c41e.json"
tag = "flippyflop-ERC20AllowanceModel"
qualified_path = "origami_token::components::token::erc20::erc20_allowance::erc_20_allowance_model"
manifest_name = "flippyflop-ERC20AllowanceModel-55d0c41e"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "spender"
type = "ContractAddress"
key = true

[[members]]
name = "amount"
type = "u256"
key = false
