kind = "DojoContract"
class_hash = "0x36d96eb5c3aef927391a701ea9219357af7d964d1ec3c0c4519615d30bcb955"
original_class_hash = "0x36d96eb5c3aef927391a701ea9219357af7d964d1ec3c0c4519615d30bcb955"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/flippyflop-game-23e1ad43.json"
reads = []
writes = []
init_calldata = []
tag = "flippyflop-game"
systems = [
    "lock",
    "unlock",
]
manifest_name = "flippyflop-game-23e1ad43"
