kind = "DojoContract"
class_hash = "0x683a4555da17fdd63478e6b096f7cbb3fc8b02dcfdaa361fb2c712a14241abb"
original_class_hash = "0x683a4555da17fdd63478e6b096f7cbb3fc8b02dcfdaa361fb2c712a14241abb"
base_class_hash = "0x0"
abi = "manifests/mainnet/base/abis/contracts/flippyflop-Flip-6bd3ed9d.json"
reads = []
writes = []
init_calldata = []
tag = "flippyflop-Flip"
systems = [
    "burn",
    "burn_from",
    "mint",
    "before_update",
    "after_update",
]
manifest_name = "flippyflop-Flip-6bd3ed9d"
