tag = "flippyflop-actions"
writes = [
    "flippyflop-Tile",
    "flippyflop-Game",
    "flippyflop-Claim",
    "flippyflop-ERC20MetadataModel",
    "flippyflop-ERC20BalanceModel",
    "flippyflop-ERC20AllowanceModel",
    "flippyflop-ERC20BridgeableModel",
    "flippyflop-InitializableModel",
]
