kind = "DojoContract"
class_hash = "0x71ff3db9b03a630288fa3c3d9841120077f75a90019ddc5b94e7ebdf0799c11"
original_class_hash = "0x71ff3db9b03a630288fa3c3d9841120077f75a90019ddc5b94e7ebdf0799c11"
base_class_hash = "0x0"
abi = "manifests/sepolia/base/abis/contracts/flippyflop-actions-4407e5f5.json"
reads = []
writes = []
init_calldata = []
tag = "flippyflop-actions"
systems = [
    "flip",
    "flop",
    "claim",
]
manifest_name = "flippyflop-actions-4407e5f5"
