kind = "DojoContract"
class_hash = "0x21460d50d87baf49fa111c916498ecba5432dd91b1c748e84a2ec504dca748"
original_class_hash = "0x21460d50d87baf49fa111c916498ecba5432dd91b1c748e84a2ec504dca748"
base_class_hash = "0x0"
abi = "manifests/sepolia/base/abis/contracts/flippyflop-actions-4407e5f5.json"
reads = []
writes = []
init_calldata = []
tag = "flippyflop-actions"
systems = [
    "flip",
    "flop",
    "claim",
]
manifest_name = "flippyflop-actions-4407e5f5"
