kind = "DojoModel"
class_hash = "0x4f60ae83d8ae292f332022f258e627e52e113cb5377ec9b01dc3912dae63c42"
original_class_hash = "0x4f60ae83d8ae292f332022f258e627e52e113cb5377ec9b01dc3912dae63c42"
abi = "manifests/mainnet/base/abis/models/flippyflop-ERC20BridgeableModel-1ad0a3e6.json"
tag = "flippyflop-ERC20BridgeableModel"
qualified_path = "flippyflop::tokens::flip::erc_20_bridgeable_model"
manifest_name = "flippyflop-ERC20BridgeableModel-1ad0a3e6"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "l2_bridge_address"
type = "ContractAddress"
key = false
