kind = "DojoContract"
class_hash = "0x76baa1940f0bce06e2d569d14bfca1321df510aa8523d8a0a49dc635b1fa9e8"
original_class_hash = "0x76baa1940f0bce06e2d569d14bfca1321df510aa8523d8a0a49dc635b1fa9e8"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/flippyflop-game-23e1ad43.json"
reads = []
writes = []
init_calldata = []
tag = "flippyflop-game"
systems = ["set_game"]
manifest_name = "flippyflop-game-23e1ad43"
