kind = "DojoContract"
class_hash = "0x1df1aac32ac918251f349d0a860f7e75e967bf2d4a3464dac7c6a56c04abecf"
original_class_hash = "0x1df1aac32ac918251f349d0a860f7e75e967bf2d4a3464dac7c6a56c04abecf"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/flippyflop-actions-4407e5f5.json"
reads = []
writes = []
init_calldata = []
tag = "flippyflop-actions"
systems = [
    "flip",
    "flop",
    "claim",
]
manifest_name = "flippyflop-actions-4407e5f5"
