kind = "DojoContract"
class_hash = "0x387fe3fc7f75da12e272a16afa22084a793c954b0171ea7256d5643b27ae6b0"
original_class_hash = "0x387fe3fc7f75da12e272a16afa22084a793c954b0171ea7256d5643b27ae6b0"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/flippyflop-game-23e1ad43.json"
reads = []
writes = []
init_calldata = []
tag = "flippyflop-game"
systems = ["set_game"]
manifest_name = "flippyflop-game-23e1ad43"
